[Interface]
Address = 10.66.66.5/32
PrivateKey = <REDACTED>
# Enmascarar el trafico del contenedor Kali a la IP de la interfaz (10.66.66.5)
# para que el cryptokey-routing de VPS2 (AllowedIPs=10.66.66.5/32) lo acepte.
PostUp = iptables -t nat -A POSTROUTING -o %i -j MASQUERADE
PostDown = iptables -t nat -D POSTROUTING -o %i -j MASQUERADE

[Peer]
PublicKey = <REDACTED>
PresharedKey = <REDACTED>
Endpoint = 203.0.113.14:50173
AllowedIPs = 10.66.66.0/24, 172.30.0.0/24
PersistentKeepalive = 25
